#!/bin/sh

# Append ~/bin to PATH
PATH=$PATH:~/bin

echo "----------------- POST-RECEIVE HOOK v1.0 ---------------"
echo "Author: @AlexDev404 (Immanuel Garcia)"
echo "You can either safely press CTRL+C or wait for this to complete"

echo "[STEP 1/5]: Resetting tree to HEAD"
git reset --hard
git reflog expire --expire=all --all
git gc --prune=now --aggressive

echo "[STEP 2/5]: Installing dependencies in the background..."
npm install &  # Run npm install in the background

install_pid=$!  # Store the process ID of npm install

echo "[STEP 3/5]: Waiting for npm install to complete..."
wait $install_pid  # Wait for npm install to finish

echo "[STEP 4/5]: Killing the old NodeJS process..."
pkill -f node

echo "[STEP 5/5]: Starting services..."
nohup npm start &> npm_start.log &  # Start npm in the background and log output

echo "-------------- HAVE A NICE DAY :) -------------"
exit
